CREATE TABLE `shared_files` (
	`id` int AUTO_INCREMENT NOT NULL,
	`appUserId` int NOT NULL,
	`userActionId` int,
	`title` varchar(200),
	`titleHe` varchar(200),
	`description` text,
	`descriptionHe` text,
	`category` varchar(64),
	`tags` varchar(500),
	`feature` varchar(32),
	`dxfUrl` text NOT NULL,
	`previewImageUrl` text,
	`svgPreview` mediumtext,
	`sourceImageUrl` text,
	`lineCount` int DEFAULT 0,
	`downloadCount` int DEFAULT 0,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`adminNote` text,
	`reviewedByAdminId` int,
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shared_files_id` PRIMARY KEY(`id`)
);
